services:
  alejoide-web:
    image: alejoide/alejoide-web:latest
    container_name: alejoide-web
    restart: unless-stopped
    env_file:
      - ./config/backend/.env
    networks:
      - nginx-proxy

  # projects-api:
  #   image: alejoide/projects-api:latest
  #   container_name: projects-api
  #   restart: unless-stopped
  #   env_file:
  #     - ./config/projects-api/.env

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
